---
version: 2.1

jobs:

  build-macos:
    macos:
      xcode: "12.5.1"
    environment:
      - OCPN_TARGET: macos
      - CMAKE_BUILD_PARALLEL_LEVEL: 2
    steps:
      - checkout
      - run: ci/circleci-build-macos.sh
      - run: >
          sh -c "otool -L build-osx/app/*/OpenCPN.app/Contents/PlugIns/*.dylib"
      - run: cd build-osx; /bin/bash < upload.sh
      - run: ci/git-push.sh  build-osx

std-filters: &std-filters
  filters:
    branches:
      ignore:
        - tmp
        - /tmp-.*/

workflows:
  version: 2
  build_all:
    jobs:

      - build-macos:
          <<: *std-filters
